services:
  app:
    build: .
    container_name: synaxic-app
    profiles: ["prod"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/synaxic
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTG-RES_PASSWORD}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - synaxic-network

  postgres:
    image: postgres:16-alpine
    container_name: synaxic-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - synaxic-network

  redis:
    image: redis:7-alpine
    container_name: synaxic-redis
    ports:
      - "6379:6379"
    networks:
      - synaxic-network

  prometheus-prod:
    image: prom/prometheus:latest
    container_name: synaxic-prometheus
    profiles: ["prod"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - synaxic-network

  prometheus-dev:
    image: prom/prometheus:latest
    container_name: synaxic-prometheus-dev
    profiles: ["dev"]
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - synaxic-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: synaxic-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - synaxic-network


volumes:
  postgres_data:
  grafana_data:

networks:
  synaxic-network:
    driver: bridge